package org.algorithmx.rules.event;

public enum EventType {

    ON_CONDITION, ON_FUNCTION, ON_ACTION,

    RULE_START, RULE_END, RULE_PRE_CONDITION_START, RULE_PRE_CONDITION_END, RULE_CONDITION_START, RULE_CONDITION_END,
    RULE_ACTION_START, RULE_ACTION_END, RULE_OTHERWISE_ACTION_START, RULE_OTHERWISE_ACTION_END,

    RULE_SET_START, RULE_SET_END, RULE_SET_PRE_CONDITION_START, RULE_SET_PRE_CONDITION_END,
    RULE_SET_PRE_ACTION_START, RULE_SET_PRE_ACTION_END, RULE_SET_ERROR,
    RULE_SET_ERROR_CONDITION_START, RULE_SET_ERROR_CONDITION_END, RULE_SET_STOP_CONDITION_START,
    RULE_SET_STOP_CONDITION_END, RULE_SET_POST_ACTION_START, RULE_SET_POST_ACTION_END;
}
